using DesafioPOO.Models;

// TODO: Realizar os testes com as classes Nokia e Iphone
Smartphone nokia = new Nokia("123456789", "Nokia 3310", "123456789", 16);
nokia.Ligar();  // Saída: Ligando...  
nokia.ReceberLigacao();  // Saída: Recebendo ligação...
nokia.InstalarAplicativo("Monopoly Go");  // Saída: Instalando aplicativo Monopoly Go no Nokia...

Smartphone iphone = new Iphone("987654321", "Iphone 12", "987654321", 128);
iphone.Ligar();  // Saída: Ligando...
iphone.ReceberLigacao();  // Saída: Recebendo ligação...
iphone.InstalarAplicativo("Android");  // Saída: Instalando aplicativo Android no Iphone...